export const GET_LIST_TESTING_REQUEST = 'GET_LIST_TESTING_REQUEST';
export const GET_LIST_TESTING_SUCCESS = 'GET_LIST_TESTING_SUCCESS';
export const GET_LIST_TESTING_FAILURE = 'GET_LIST_TESTING_FAILURE';
